In [ ]:
#Enlace a la información
#https://www.kaggle.com/code/residentmario/indexing-selecting-assigning

In [1]:
import pandas as pd

In [2]:
titanic_pasajeros = pd.read_csv("C:/Users/xabie/Desktop/gitProyectos/Python/datasets/Titanic-Dataset.csv" )

In [ ]:
titanic_pasajeros.head()

In [ ]:
titanic_pasajeros.Survived

In [ ]:
titanic_pasajeros['Survived']

In [ ]:
titanic_pasajeros["Name"][0]

In [ ]:
titanic_pasajeros.iloc[0]
#Iloc engancha la fila entera, con el índice de parámetro

In [ ]:
titanic_pasajeros.iloc[0 , 4] #fila primero, columa segundo

In [ ]:
#Para coger toda una columa, o fila se haría así
titanic_pasajeros.iloc[: , 1] #Así se sacan todos los datos de una columa
titanic_pasajeros.iloc[1 , :] #asi todos los datos de una fila

In [ ]:
titanic_pasajeros.iloc[:3 , :] #Esto es básicamente, todo hasta el 3
#De hacerlo al revés sería, todo menos los tres primeros .

In [ ]:
titanic_pasajeros.iloc[1:3 , 0 ] #ESto quiere decir del índice 1 (segunda fila , hasta la tercera, pero sólo el id (primera columna))

In [ ]:
titanic_pasajeros.iloc[[0 , 1 ,2 ,3 ] , 3] #Todos  los nombres de los 4 primeros

In [ ]:
titanic_pasajeros.iloc[-5 : ] #Los últimos 5
#si esta a la izquierda del los dos puntos, es

In [ ]:
#Acceso a datos usando el índice String
titanic_pasajeros.loc[0 , 'Name']

In [ ]:
titanic_pasajeros.loc[: , ['Name' , 'Survived']]
#TODAS LAS FILAS, QUE TENGAN ESOS CAMPOS DE COLUMNA

In [ ]:
titanic_pasajeros.set_index("Name")
#Para usar de índice una etiqueta (nombres de las columnas)

In [ ]:
titanic_pasajeros.set_index("Pclass")

In [ ]:
titanic_pasajeros['Name'] == 'male'

In [5]:
titanic_pasajeros.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
titanic_pasajeros.loc[(titanic_pasajeros['Sex'] == 'male') & (titanic_pasajeros['Survived']) & (titanic_pasajeros['Fare'] > 20)]

In [ ]:
titanic_pasajeros.loc[(titanic_pasajeros['Fare'] > 2550 ) | (titanic_pasajeros['Sex'] == 'female')]

In [6]:
titanic_pasajeros.loc[titanic_pasajeros['Cabin'].isin(['C123' , 'C85'])]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
137,138,0,1,"Futrelle, Mr. Jacques Heath",male,37.0,1,0,113803,53.1000,C123,S

In [11]:
titanic_pasajeros.loc[titanic_pasajeros['Cabin'].notnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [16]:
titanic_pasajeros['Name'] = 'pasajero'

In [17]:
titanic_pasajeros.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,pasajero1,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,pasajero1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,pasajero1,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,pasajero1,female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,pasajero1,male,35.0,0,0,373450,8.0500,NaN,S

In [18]:
titanic_pasajeros['PassengerId'] = range(len(titanic_pasajeros) , 0 , -1)

In [19]:
titanic_pasajeros.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,891,0,3,pasajero1,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,890,1,1,pasajero1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,889,1,3,pasajero1,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,888,1,1,pasajero1,female,35.0,1,0,113803,53.1000,C123,S
4,887,0,3,pasajero1,male,35.0,0,0,373450,8.0500,NaN,S